# ── generate_lxc_config ───────────────────────────────────────────────────────
# 修正版本，整合所有踩過的坑：
# 1. lxc.include = 覆蓋 /etc/lxc/default.conf（Void Linux 預設有 veth 衝突）
# 2. 拿掉 /tmp /sys /dev bind mount，改用 lxc.mount.auto
# 3. lxc.tty.max + lxc.pty.max 讓 devpts 正常運作
# 4. namespace.share.pid 拿掉（會造成 hang）
# 5. Wayland/PipeWire/PulseAudio socket 加 optional（沒 GUI session 不炸）
# 6. X11 socket mount
# ─────────────────────────────────────────────────────────────────────────────
generate_lxc_config()
{
    wayland_display="${WAYLAND_DISPLAY:-wayland-0}"
    xdg_runtime="/run/user/${container_user_uid}"
    wayland_socket="${xdg_runtime}/${wayland_display}"
    pipewire_socket="${xdg_runtime}/pipewire-0"
    pulse_socket="${xdg_runtime}/pulse/native"
    x11_socket="/tmp/.X11-unix"

    cat << LXCCONF
# lxcbox config — generated by lxcbox-create ${version}
# Container: ${container_name}

# ── 覆蓋 /etc/lxc/default.conf ────────────────────────────────────────────────
# 清掉發行版預設的 veth 網路設定，避免跟 lxc.net.0.type = none 衝突
lxc.include =

# ── Identity ──────────────────────────────────────────────────────────────────
lxc.uts.name = ${container_hostname}

# ── Init ──────────────────────────────────────────────────────────────────────
lxc.init.cmd = /bin/sleep infinity

# ── Capabilities / security ───────────────────────────────────────────────────
lxc.cap.drop =

# ── Network ───────────────────────────────────────────────────────────────────
# 共用 Host 網路 namespace（不建虛擬網卡）
lxc.net.0.type = none

# ── TTY / PTY ─────────────────────────────────────────────────────────────────
# 讓 container 有足夠的 pty（xterm、tmux 等需要）
lxc.tty.max = 4
lxc.pty.max = 1024

# ── Filesystem ────────────────────────────────────────────────────────────────
lxc.rootfs.path = dir:${container_rootfs}

# ── 自動掛載（proc / sys / cgroup）────────────────────────────────────────────
# 注意：不要手動 bind mount /sys /dev /tmp，讓 LXC 自己管理
lxc.mount.auto = proc:mixed sys:mixed cgroup:mixed

# ── 網路設定檔（跟 Host 同步）────────────────────────────────────────────────
lxc.mount.entry = /etc/hosts etc/hosts none bind,ro,create=file 0 0
lxc.mount.entry = /etc/resolv.conf etc/resolv.conf none bind,ro,create=file 0 0
lxc.mount.entry = /etc/hostname etc/hostname none bind,ro,create=file 0 0

# ── Host root（distrobox 風格，/run/host）────────────────────────────────────
lxc.mount.entry = / run/host none bind,ro,rslave,create=dir 0 0

# ── User home ─────────────────────────────────────────────────────────────────
lxc.mount.entry = ${effective_home} ${effective_home#/} none bind,rw,rslave,create=dir 0 0

# ── XDG_RUNTIME_DIR（整個目錄，包含所有 socket）──────────────────────────────
$([ -d "${xdg_runtime}" ] \
    && printf "lxc.mount.entry = %s %s none bind,rw,rslave,create=dir 0 0" \
        "${xdg_runtime}" "${xdg_runtime#/}" \
    || printf "# XDG_RUNTIME_DIR %s not present (no GUI session)" "${xdg_runtime}")

# ── X11 socket ────────────────────────────────────────────────────────────────
$([ -d "${x11_socket}" ] \
    && printf "lxc.mount.entry = %s %s none bind,rw,rslave,create=dir 0 0" \
        "${x11_socket}" "${x11_socket#/}" \
    || printf "# X11 socket not found at %s" "${x11_socket}")

# ── lxcbox helper scripts ─────────────────────────────────────────────────────
$([ -n "${lxcbox_init_path}" ]    && printf "lxc.mount.entry = %s usr/bin/lxcbox-init none bind,ro,create=file 0 0" "${lxcbox_init_path}")
$([ -n "${lxcbox_export_path}" ]  && printf "lxc.mount.entry = %s usr/bin/lxcbox-export none bind,ro,create=file 0 0" "${lxcbox_export_path}")
$([ -n "${lxcbox_hostexec_path}" ] && printf "lxc.mount.entry = %s usr/bin/lxcbox-host-exec none bind,ro,create=file 0 0" "${lxcbox_hostexec_path}")

# ── Additional volumes ────────────────────────────────────────────────────────
$(for vol in ${container_additional_volumes:-}; do
    host_path="$(echo "${vol}" | cut -d: -f1)"
    cont_path="$(echo "${vol}" | cut -d: -f2)"
    opts="$(echo "${vol}" | cut -d: -f3)"
    opts="${opts:-rw}"
    printf "lxc.mount.entry = %s %s none bind,%s,create=dir 0 0\n" \
        "${host_path}" "${cont_path#/}" "${opts}"
done)

# ── Environment ───────────────────────────────────────────────────────────────
lxc.environment = SHELL=$(basename "${SHELL:-/bin/bash}")
lxc.environment = HOME=${effective_home}
lxc.environment = USER=${container_user_name}
lxc.environment = CONTAINER_ID=${container_name}
lxc.environment = WAYLAND_DISPLAY=${wayland_display}
lxc.environment = XDG_RUNTIME_DIR=${xdg_runtime}
lxc.environment = TERMINFO_DIRS=/usr/share/terminfo:/run/host/usr/share/terminfo
lxc.environment = DBUS_SESSION_BUS_ADDRESS=unix:path=${xdg_runtime}/bus
lxc.environment = DISPLAY=${DISPLAY:-:0}
lxc.environment = XAUTHORITY=${effective_home}/.Xauthority

LXCCONF
}
